@api = http://localhost:5000

###
GET {{api}}/auth/profile

###
POST {{api}}/auth/signup
Content-Type: application/json

{
    "username": "Neil",
    "email": "neil@gmail.com",
    "password" : "123"
}

###
POST {{api}}/auth/signup
Content-Type: application/json

{
    "username": "Cordero",
    "email": "cordero@gmail.com",
    "password" : "1234"
}

###
POST {{api}}/auth/signin
Content-Type: application/json

{
    "email": "cordero@gmail.com",
    "password" : "1234"
}

###
GET {{api}}/auth/profile
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGE3MzQ4ZjZjZjA0NDA3ZDQwYzMxNGEiLCJpYXQiOjE2MjE1Nzc2MzMsImV4cCI6MTYyMTY2NDAzM30.wlBJ182-Yk_SJnsQDrwO0H_-wU_Erk5rQ6kMTL6_FbE


